/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boardgame;

import java.lang.reflect.*;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Furkan
 */
public class BoardGame extends javax.swing.JFrame {

    /**
     * Creates new form BoardGame_
     */
    public Player player1;
    public Player player2;
    
    public BoardGame() {
        initComponents();
        this.setResizable(false);
        this.player1 = new Player(true);
        this.player2 = new Player(false);
        this.setBoard(this.player1);
        this.setBoard(this.player2);
    }
    public void setBoard(Player pl) {
        try {
            ArrayList<ButtonField> but = new ArrayList<ButtonField>();
            Class c = Class.forName(this.getClass().getName());
            Field[] f = c.getDeclaredFields();
            for (Field f1 : f) {
                if (!f1.getType().equals(JButton.class)) continue;
                JButton b = (JButton)f1.get(this);
                ButtonField bf = new ButtonField(b, f1);
                but.add(bf);
            }
            for (Piece p : pl.pieces) {
                String s = "L" + p.layer + "_" + p.order;
                for (ButtonField bu : but) {
                    if (!bu.field.getName().equals(s)) continue;
                    if (pl.isOne) {
                        bu.button.setIcon(new ImageIcon(this.getClass().getResource("/pictures/black.png")));
                        continue;
                    }
                    bu.button.setIcon(new ImageIcon(this.getClass().getResource("/pictures/yellow.png")));
                }
            }
        }catch(Exception e){
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L0_0 = new javax.swing.JButton();
        L1_0 = new javax.swing.JButton();
        L1_1 = new javax.swing.JButton();
        L1_2 = new javax.swing.JButton();
        L1_3 = new javax.swing.JButton();
        L1_4 = new javax.swing.JButton();
        L1_5 = new javax.swing.JButton();
        L1_6 = new javax.swing.JButton();
        L1_7 = new javax.swing.JButton();
        L2_0 = new javax.swing.JButton();
        L2_1 = new javax.swing.JButton();
        L2_2 = new javax.swing.JButton();
        L2_3 = new javax.swing.JButton();
        L2_4 = new javax.swing.JButton();
        L2_5 = new javax.swing.JButton();
        L2_6 = new javax.swing.JButton();
        L2_7 = new javax.swing.JButton();
        L3_0 = new javax.swing.JButton();
        L3_1 = new javax.swing.JButton();
        L3_2 = new javax.swing.JButton();
        L3_3 = new javax.swing.JButton();
        L3_4 = new javax.swing.JButton();
        L3_5 = new javax.swing.JButton();
        L3_6 = new javax.swing.JButton();
        L3_7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        L0_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/white.png"))); // NOI18N
        L0_0.setMaximumSize(new java.awt.Dimension(32, 32));
        L0_0.setMinimumSize(new java.awt.Dimension(32, 32));
        L0_0.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(L0_0);
        L0_0.setBounds(390, 290, 32, 32);

        L1_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/white.png"))); // NOI18N
        L1_0.setMaximumSize(new java.awt.Dimension(32, 32));
        L1_0.setMinimumSize(new java.awt.Dimension(32, 32));
        L1_0.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(L1_0);
        L1_0.setBounds(390, 200, 32, 32);

        L1_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/white.png"))); // NOI18N
        L1_1.setMaximumSize(new java.awt.Dimension(32, 32));
        L1_1.setMinimumSize(new java.awt.Dimension(32, 32));
        L1_1.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(L1_1);
        L1_1.setBounds(450, 230, 32, 32);

        L1_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/white.png"))); // NOI18N
        L1_2.setMaximumSize(new java.awt.Dimension(32, 32));
        L1_2.setMinimumSize(new java.awt.Dimension(32, 32));
        L1_2.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(L1_2);
        L1_2.setBounds(460, 290, 32, 32);

        L1_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/white.png"))); // NOI18N
        L1_3.setMaximumSize(new java.awt.Dimension(32, 32));
        L1_3.setMinimumSize(new java.awt.Dimension(32, 32));
        L1_3.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(L1_3);
        L1_3.setBounds(450, 340, 32, 32);

        L1_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/white.png"))); // NOI18N
        L1_4.setMaximumSize(new java.awt.Dimension(32, 32));
        L1_4.setMinimumSize(new java.awt.Dimension(32, 32));
        L1_4.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(L1_4);
        L1_4.setBounds(390, 370, 32, 32);

        L1_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/white.png"))); // NOI18N
        L1_5.setMaximumSize(new java.awt.Dimension(32, 32));
        L1_5.setMinimumSize(new java.awt.Dimension(32, 32));
        L1_5.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(L1_5);
        L1_5.setBounds(320, 340, 32, 32);

        L1_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/white.png"))); // NOI18N
        L1_6.setMaximumSize(new java.awt.Dimension(32, 32));
        L1_6.setMinimumSize(new java.awt.Dimension(32, 32));
        L1_6.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(L1_6);
        L1_6.setBounds(300, 290, 32, 32);

        L1_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/white.png"))); // NOI18N
        L1_7.setMaximumSize(new java.awt.Dimension(32, 32));
        L1_7.setMinimumSize(new java.awt.Dimension(32, 32));
        L1_7.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(L1_7);
        L1_7.setBounds(320, 230, 32, 32);

        L2_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/white.png"))); // NOI18N
        L2_0.setMaximumSize(new java.awt.Dimension(32, 32));
        L2_0.setMinimumSize(new java.awt.Dimension(32, 32));
        L2_0.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(L2_0);
        L2_0.setBounds(390, 140, 32, 32);

        L2_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/white.png"))); // NOI18N
        L2_1.setMaximumSize(new java.awt.Dimension(32, 32));
        L2_1.setMinimumSize(new java.awt.Dimension(32, 32));
        L2_1.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(L2_1);
        L2_1.setBounds(500, 200, 32, 32);

        L2_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/white.png"))); // NOI18N
        L2_2.setMaximumSize(new java.awt.Dimension(32, 32));
        L2_2.setMinimumSize(new java.awt.Dimension(32, 32));
        L2_2.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(L2_2);
        L2_2.setBounds(530, 290, 32, 32);

        L2_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/white.png"))); // NOI18N
        L2_3.setMaximumSize(new java.awt.Dimension(32, 32));
        L2_3.setMinimumSize(new java.awt.Dimension(32, 32));
        L2_3.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(L2_3);
        L2_3.setBounds(510, 370, 32, 32);

        L2_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/white.png"))); // NOI18N
        L2_4.setMaximumSize(new java.awt.Dimension(32, 32));
        L2_4.setMinimumSize(new java.awt.Dimension(32, 32));
        L2_4.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(L2_4);
        L2_4.setBounds(390, 430, 32, 32);

        L2_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/white.png"))); // NOI18N
        L2_5.setMaximumSize(new java.awt.Dimension(32, 32));
        L2_5.setMinimumSize(new java.awt.Dimension(32, 32));
        L2_5.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(L2_5);
        L2_5.setBounds(260, 370, 32, 32);

        L2_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/white.png"))); // NOI18N
        L2_6.setMaximumSize(new java.awt.Dimension(32, 32));
        L2_6.setMinimumSize(new java.awt.Dimension(32, 32));
        L2_6.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(L2_6);
        L2_6.setBounds(240, 290, 32, 32);

        L2_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/white.png"))); // NOI18N
        L2_7.setMaximumSize(new java.awt.Dimension(32, 32));
        L2_7.setMinimumSize(new java.awt.Dimension(32, 32));
        L2_7.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(L2_7);
        L2_7.setBounds(260, 200, 32, 32);

        L3_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/white.png"))); // NOI18N
        L3_0.setMaximumSize(new java.awt.Dimension(32, 32));
        L3_0.setMinimumSize(new java.awt.Dimension(32, 32));
        L3_0.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(L3_0);
        L3_0.setBounds(390, 80, 32, 32);

        L3_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/white.png"))); // NOI18N
        L3_1.setMaximumSize(new java.awt.Dimension(32, 32));
        L3_1.setMinimumSize(new java.awt.Dimension(32, 32));
        L3_1.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(L3_1);
        L3_1.setBounds(550, 160, 32, 32);

        L3_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/white.png"))); // NOI18N
        L3_2.setMaximumSize(new java.awt.Dimension(32, 32));
        L3_2.setMinimumSize(new java.awt.Dimension(32, 32));
        L3_2.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(L3_2);
        L3_2.setBounds(600, 290, 32, 32);

        L3_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/white.png"))); // NOI18N
        L3_3.setMaximumSize(new java.awt.Dimension(32, 32));
        L3_3.setMinimumSize(new java.awt.Dimension(32, 32));
        L3_3.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(L3_3);
        L3_3.setBounds(560, 410, 32, 32);

        L3_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/white.png"))); // NOI18N
        L3_4.setMaximumSize(new java.awt.Dimension(32, 32));
        L3_4.setMinimumSize(new java.awt.Dimension(32, 32));
        L3_4.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(L3_4);
        L3_4.setBounds(390, 500, 32, 32);

        L3_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/white.png"))); // NOI18N
        L3_5.setMaximumSize(new java.awt.Dimension(32, 32));
        L3_5.setMinimumSize(new java.awt.Dimension(32, 32));
        L3_5.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(L3_5);
        L3_5.setBounds(210, 420, 32, 32);

        L3_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/white.png"))); // NOI18N
        L3_6.setMaximumSize(new java.awt.Dimension(32, 32));
        L3_6.setMinimumSize(new java.awt.Dimension(32, 32));
        L3_6.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(L3_6);
        L3_6.setBounds(180, 290, 32, 32);

        L3_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/white.png"))); // NOI18N
        L3_7.setMaximumSize(new java.awt.Dimension(32, 32));
        L3_7.setMinimumSize(new java.awt.Dimension(32, 32));
        L3_7.setPreferredSize(new java.awt.Dimension(32, 32));
        getContentPane().add(L3_7);
        L3_7.setBounds(210, 160, 32, 32);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/background.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoardGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoardGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoardGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoardGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoardGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton L0_0;
    private javax.swing.JButton L1_0;
    private javax.swing.JButton L1_1;
    private javax.swing.JButton L1_2;
    private javax.swing.JButton L1_3;
    private javax.swing.JButton L1_4;
    private javax.swing.JButton L1_5;
    private javax.swing.JButton L1_6;
    private javax.swing.JButton L1_7;
    private javax.swing.JButton L2_0;
    private javax.swing.JButton L2_1;
    private javax.swing.JButton L2_2;
    private javax.swing.JButton L2_3;
    private javax.swing.JButton L2_4;
    private javax.swing.JButton L2_5;
    private javax.swing.JButton L2_6;
    private javax.swing.JButton L2_7;
    private javax.swing.JButton L3_0;
    private javax.swing.JButton L3_1;
    private javax.swing.JButton L3_2;
    private javax.swing.JButton L3_3;
    private javax.swing.JButton L3_4;
    private javax.swing.JButton L3_5;
    private javax.swing.JButton L3_6;
    private javax.swing.JButton L3_7;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
